language: python
python:
  - "3.12"
# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - export SECRET_KEY="$SECRET_KEY" 
  - python manage.py test 