language: python
python:
  - "3.12"
# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script: 
    - SECRET_KEY="placeholdersecretkey" python manage.py test 