# Generated by Django 3.2.25 on 2024-06-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('event_date', models.DateTimeField(blank=True, null=True, verbose_name='Event Date and Time')),
                ('event_time', models.DateTimeField(blank=True, null=True, verbose_name='Event Time')),
                ('description', models.TextField()),
                ('capacity', models.IntegerField()),
                ('tickets_sold', models.IntegerField(default=0)),
            ],
        ),
    ]
