# Generated by Django 3.2.25 on 2024-06-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_image_alt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='event_datetime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_time',
        ),
    ]
