# Generated by Django 3.2.25 on 2024-06-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20240626_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_datetime']},
        ),
        migrations.AddField(
            model_name='event',
            name='alt_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
