# Generated by Django 5.0.6 on 2024-09-02 14:42

import checkout.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=20)),
                ('town_or_city', models.CharField(max_length=40)),
                ('street_address1', models.CharField(max_length=80)),
                ('street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('county', models.CharField(max_length=80, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('original_bag', models.TextField(default='')),
                ('stripe_pid', models.CharField(default='', max_length=254)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EventOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_to_host', models.TextField(blank=True, default='')),
                ('attendee_name', models.CharField(blank=True, default='', max_length=80)),
                ('quantity', models.IntegerField(default=0)),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.event')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_lineitems', to='checkout.order')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_message', models.TextField(blank=True, default='')),
                ('note_to_seller', models.TextField(blank=True, default='')),
                ('quantity', models.IntegerField(default=0)),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('delivery_method', models.CharField(blank=True, choices=[('delivery', 'Delivery'), ('pickup', 'Shop Pickup')], max_length=20, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True, validators=[checkout.validators.validate_date])),
                ('delivery_name', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_street_address1', models.CharField(blank=True, max_length=80, null=True)),
                ('delivery_street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('delivery_town_or_city', models.CharField(blank=True, max_length=40, null=True)),
                ('delivery_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_county', models.CharField(blank=True, max_length=80, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lineitems', to='checkout.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant')),
            ],
        ),
    ]
