# Generated by Django 5.0.6 on 2024-07-16 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_orderlineitem_delete_orderlineitemproduct'),
        ('products', '0018_remove_productvariant_card_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_to_host', models.TextField(blank=True, default='')),
                ('quantity', models.IntegerField(default=0)),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.event')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_lineitems', to='checkout.order')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_message', models.TextField(blank=True, default='')),
                ('note_to_seller', models.TextField(blank=True, default='')),
                ('quantity', models.IntegerField(default=0)),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('delivery_method', models.CharField(blank=True, choices=[('delivery', 'Delivery'), ('pickup', 'Shop Pickup')], max_length=20, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_name', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_street_address1', models.CharField(blank=True, max_length=80, null=True)),
                ('delivery_street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('delivery_town_or_city', models.CharField(blank=True, max_length=40, null=True)),
                ('delivery_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_county', models.CharField(blank=True, max_length=80, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lineitems', to='checkout.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderLineItem',
        ),
    ]
