# Generated by Django 5.0.6 on 2024-07-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_order_county_alter_order_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorderlineitem',
            name='attendee_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
