# Generated by Django 3.2.25 on 2024-06-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_alt',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
    ]
