# Generated by Django 3.2.25 on 2024-06-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240625_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_alt',
        ),
    ]
