# Generated by Django 3.2.25 on 2024-06-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the gift card amount', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_gift_card',
            field=models.BooleanField(default=False),
        ),
    ]
