# Generated by Django 3.2.25 on 2024-06-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alt_text',
            field=models.TextField(default=''),
        ),
    ]
