# Generated by Django 3.2.25 on 2024-06-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_alt_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['friendly_name']},
        ),
    ]
