# Generated by Django 5.0.6 on 2024-07-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('event_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Event Date and Time')),
                ('description', models.TextField()),
                ('capacity', models.IntegerField()),
                ('tickets_sold', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('alt_text', models.TextField(default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['event_datetime'],
            },
        ),
    ]
