# Generated by Django 5.0.6 on 2024-07-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_infinite_stock',
            field=models.BooleanField(default=False, help_text='Check if stock is flowers'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Number of items available in stock'),
        ),
    ]
