# Generated by Django 5.0.6 on 2024-07-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_productvariant_is_active_productvariant_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='card_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='note_to_seller',
            field=models.TextField(blank=True, null=True),
        ),
    ]
