# Generated by Django 5.0.6 on 2024-07-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_productvariant_card_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='card_message',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='note_to_seller',
        ),
    ]
