# Generated by Django 5.0.6 on 2024-08-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_product_is_infinite_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_infinite_stock',
            field=models.BooleanField(default=False, help_text='Check if stock is a bouquet'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_medium',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_infinite_stock',
            field=models.BooleanField(default=False, help_text='Check if stock is a bouquet'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Number of items available in stock for this size'),
        ),
    ]
