# Generated by Django 5.0.6 on 2024-08-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_is_infinite_stock_product_price_medium_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_medium',
            new_name='price',
        ),
    ]
