# Generated by Django 5.0.6 on 2024-08-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tickets_sold',
        ),
    ]
