# Generated by Django 5.0.6 on 2024-08-20 20:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_remove_event_capacity_remove_event_tickets_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='alt_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Event Date and Time'),
            preserve_default=False,
        ),
    ]
